services:
  bookstore_nginx_frontend:
    container_name: bookstore_nginx_frontend
    image: nginx:alpine
    volumes:
      - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
      - ./api/public:/app/public
    ports:
      - "${NGINX_PORT:-80}:80"
    links:
      - bookstore_php
  bookstore_nginx:
    container_name: bookstore_nginx
    depends_on:
      - bookstore_php
    image: nginx:alpine
    volumes:
      - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
      - ./api/public:/app/public
    ports:
      - "${NGINX_PORT:-80}:80"
    links:
      - bookstore_php

  bookstore_php:
    container_name: bookstore_php
    build:
      context: .
    links:
      - bookstore_mysql
    expose:
      - '9000'
    volumes:
      - './api:/app'
    restart: unless-stopped

  bookstore_mysql:
    container_name: bookstore_mysql
    image: mysql:8
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dev_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-dev_pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dev_db}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw

volumes:
  php_public: