services:
  desafio_nginx:
    container_name: desafio_nginx
    depends_on:
      - desafio_php
    image: nginx:alpine
    volumes:
      - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
      - ./api/public:/app/public
    ports:
      - "80:80"
    links:
      - desafio_php

  desafio_php:
    container_name: desafio_php
    build:
      context: .
    links:
      - desafio_mysql
    expose:
      - '9000'
    volumes:
      - '.:/app'
    restart: unless-stopped

  desafio_mysql:
    container_name: desafio_mysql
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dev_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-dev_pass}
      MYSQL_DATABASE: ${MYSQL_DB_NAME:-dev_db}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw

volumes:
  php_public: