controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authors:
    path: /authors
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'authors/index.html.twig'

authors_new:
    path: /authors/new
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'authors/new.html.twig'

authors_edit:
    path: /authors/edit
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'authors/edit.html.twig'